---

- name: prepare
  ansible.builtin.include_tasks: prepare.yml

- name: create certificate
  ansible.builtin.include_tasks: create_certificate.yml

- name: create archive
  ansible.builtin.include_tasks: create_archive.yml

- name: install
  ansible.builtin.include_tasks: install.yml
