---

- name: check, the certificate domain is specified
  assert:
    that:
      - snakeoil_domain is defined and snakeoil_domain | length != 0

- name: get system timestamp  # noqa 305
  shell: 'date +"%Y-%m-%dT%H:%M:%S"'
  register: timestamp
  no_log: true
  tags:
    - skip_ansible_lint

- name: set facts
  set_fact:
    current_date: "{{ timestamp.stdout[0:10] }}"
    current_timestamp: "{{ timestamp.stdout }}"
  no_log: true

- name: check for created snakeoil directory {{ snakeoil_directory }}/{{ snakeoil_domain }}
  delegate_to: localhost
  become: false
  stat:
    path: "{{ snakeoil_directory }}/{{ snakeoil_domain }}"
  register: _snakeoil_directory_created

- name: check for created pem {{ snakeoil_directory }}/{{ snakeoil_domain }}/{{ snakeoil_domain }}.pem
  delegate_to: localhost
  become: false
  stat:
    path: "{{ snakeoil_directory }}/{{ snakeoil_domain }}/{{ snakeoil_domain }}.pem"
  register: _certificate_created
  when: _snakeoil_directory_created is defined and _snakeoil_directory_created.stat is defined and _snakeoil_directory_created.stat.exists

- name: remove old temporary path '{{ snakeoil_directory }}'
  delegate_to: localhost
  become: false
  file:
    path: "{{ snakeoil_directory }}/{{ snakeoil_domain }}"
    state: absent
  when: snakeoil_force

- block:

    - name: get expire date
      delegate_to: localhost
      become: false
      shell: |
        date --date="$(openssl x509 -enddate -noout -in {{ snakeoil_directory }}/{{ snakeoil_domain }}/{{ snakeoil_domain }}.pem | cut -d= -f 2)" +"%Y-%m-%dT%H:%M:%S"
      args:
        chdir: "{{ snakeoil_directory }}/{{ snakeoil_domain }}"
      register: _certificate_expire_after

    - name: set facts
      set_fact:
        expire_date: "{{ _certificate_expire_after.stdout[0:10] }}"
        expire_timestamp: "{{ _certificate_expire_after.stdout }}"
        expire_diff_days: "{{ ( (_certificate_expire_after.stdout | to_datetime('%Y-%m-%dT%H:%M:%S') - current_timestamp | to_datetime('%Y-%m-%dT%H:%M:%S')).days ) | int }}"
      no_log: true

    - debug:
        msg: "certificate expires: {{ expire_date }} (in {{ expire_diff_days }} days)"

  when: _certificate_created.stat is defined and _certificate_created.stat.exists

- name: remove '{{ snakeoil_directory }}/{{ snakeoil_domain }}' when expires days lower as 10 days
  delegate_to: localhost
  become: false
  file:
    path: "{{ snakeoil_directory }}/{{ snakeoil_domain }}"
    state: absent
  when: (
    _snakeoil_directory_created is defined and _snakeoil_directory_created.stat is defined and _snakeoil_directory_created.stat.exists and
    expire_diff_days | int <= 10 )

- block:
    - name: create temporary path
      delegate_to: localhost
      become: false
      file:
        path: "{{ snakeoil_directory }}/{{ snakeoil_domain }}"
        state: directory

    - name: create openssl config
      delegate_to: localhost
      become: false
      template:
        src: csr.j2
        dest: "{{ snakeoil_directory }}/{{ snakeoil_domain }}/{{ snakeoil_domain }}.conf"

    - name: create {{ snakeoil_domain }}.csr
      delegate_to: localhost
      become: false
      shell: |
        openssl req -new -sha512 -nodes -out {{ snakeoil_domain }}.csr -newkey rsa:4096 -keyout {{ snakeoil_domain }}.key -config {{ snakeoil_domain }}.conf
      args:
        chdir: "{{ snakeoil_directory }}/{{ snakeoil_domain }}"

    - name: create {{ snakeoil_domain }}.crt
      delegate_to: localhost
      become: false
      shell: |
        openssl x509 -in {{ snakeoil_domain }}.csr -out {{ snakeoil_domain }}.crt -req -signkey {{ snakeoil_domain }}.key -days {{ snakeoil_life_time }}
        cat {{ snakeoil_domain }}.crt {{ snakeoil_domain }}.key >> {{ snakeoil_domain }}.pem
      args:
        chdir: "{{ snakeoil_directory }}/{{ snakeoil_domain }}"

    - name: create dh.pem
      delegate_to: localhost
      become: false
      shell: |
        openssl dhparam -out dh.pem {{ snakeoil_dhparam }}
      args:
        chdir: "{{ snakeoil_directory }}/{{ snakeoil_domain }}"

  when: expire_diff_days | int <= 10 or ( _certificate_created.stat is defined and not _certificate_created.stat.exists )


- name: check for created pem {{ snakeoil_directory }}/{{ snakeoil_domain }}/{{ snakeoil_domain }}.pem
  delegate_to: localhost
  become: false
  stat:
    path: "{{ snakeoil_directory }}/{{ snakeoil_domain }}/{{ snakeoil_domain }}.pem"
  register: _certificate_created

- block:

    - name: compress directory {{ snakeoil_directory }}
      delegate_to: localhost
      become: false
      archive:
        path: "{{ snakeoil_directory }}/{{ snakeoil_domain }}"
        dest: "{{ local_tmp_directory }}/{{ snakeoil_domain }}.tgz"

    - name: propagate {{ snakeoil_domain }}.tgz
      become: true
      copy:
        src: "{{ local_tmp_directory }}/{{ snakeoil_domain }}.tgz"
        dest: "{{ deployment_tmp_directory }}/"

    - name: create {{ snakeoil_extract_to }}
      file:
        path: "{{ snakeoil_extract_to }}"
        state: directory

    - name: extract {{ snakeoil_domain }}.tgz
      unarchive:
        src: "{{ deployment_tmp_directory }}/{{ snakeoil_domain }}.tgz"
        dest: "{{ snakeoil_extract_to }}"
        remote_src: true
  tags:
    - snakeoil
  when: (
    snakeoil_extract_to is defined and snakeoil_extract_to | length != 0 and
    ( _certificate_created.stat is defined and _certificate_created.stat.exists ) )
