---

- name: check, the certificate domain is specified
  assert:
    that:
      - snakeoil_domain is defined and snakeoil_domain | length != 0

- name: define current_date and current_timestamp
  set_fact:
    current_date: "{{ ansible_date_time.iso8601[0:10] }}"
    current_timestamp: "{{ ansible_date_time.iso8601[0:19] }}"

- name: check for created snakeoil directory {{ snakeoil_local_tmp_directory }}/{{ snakeoil_domain }}
  delegate_to: localhost
  become: false
  stat:
    path: "{{ snakeoil_local_tmp_directory }}/{{ snakeoil_domain }}"
  register: _snakeoil_local_tmp_directory_created

- name: check for created pem {{ snakeoil_local_tmp_directory }}/{{ snakeoil_domain }}/{{ snakeoil_domain }}.pem
  delegate_to: localhost
  become: false
  stat:
    path: "{{ snakeoil_local_tmp_directory }}/{{ snakeoil_domain }}/{{ snakeoil_domain }}.pem"
  register: _certificate_created
  when:
    - _snakeoil_local_tmp_directory_created is defined
    - _snakeoil_local_tmp_directory_created.stat is defined
    - _snakeoil_local_tmp_directory_created.stat.exists

- name: remove old temporary path '{{ snakeoil_local_tmp_directory }}'
  delegate_to: localhost
  become: false
  file:
    path: "{{ snakeoil_local_tmp_directory }}/{{ snakeoil_domain }}"
    state: absent
  when:
    - snakeoil_force

- block:
    - name: get expire date from certificate
      delegate_to: localhost
      become: false
      snakeoil_date:
        snakeoil_directory: "{{ snakeoil_local_tmp_directory  }}"
        snakeoil_domain: "{{ snakeoil_domain  }}"
        pattern: "%Y-%m-%d"
      register: _certificate_expire_after

    - name: set facts
      set_fact:
        snakeoil_expire_date: "{{ _certificate_expire_after.expire_date }}"
        snakeoil_expire_diff_days: "{{ _certificate_expire_after.diff_days }}"

    - name: "certificat expires ..."
      debug:
        msg: "certificate expires: {{ snakeoil_expire_date }} (in {{ snakeoil_expire_diff_days }} days)"
      when:
        - snakeoil_expire_diff_days | int != 0
  when:
    - _certificate_created.stat is defined
    - _certificate_created.stat.exists

- name: remove '{{ snakeoil_local_tmp_directory }}/{{ snakeoil_domain }}' when expires days lower as 10 days
  delegate_to: localhost
  become: false
  file:
    path: "{{ snakeoil_local_tmp_directory }}/{{ snakeoil_domain }}"
    state: absent
  when:
    - _snakeoil_local_tmp_directory_created is defined
    - _snakeoil_local_tmp_directory_created.stat is defined
    - _snakeoil_local_tmp_directory_created.stat.exists
    - snakeoil_expire_diff_days | int <= 10

- block:
    - name: create temporary path
      delegate_to: localhost
      become: false
      file:
        path: "{{ snakeoil_local_tmp_directory }}/{{ snakeoil_domain }}"
        state: directory
        mode: 0o750

    - name: create openssl config
      delegate_to: localhost
      become: false
      template:
        src: csr.j2
        dest: "{{ snakeoil_local_tmp_directory }}/{{ snakeoil_domain }}/{{ snakeoil_domain }}.conf"
        mode: 0o660

    - name: create {{ snakeoil_domain }}.csr
      delegate_to: localhost
      become: false
      snakeoil_openssl:
        state: csr
        directory: "{{ snakeoil_local_tmp_directory }}"
        domain: "{{ snakeoil_domain }}"
        openssl_config: "{{ snakeoil_domain }}.conf"

    - name: create {{ snakeoil_domain }}.crt
      delegate_to: localhost
      become: false
      snakeoil_openssl:
        state: crt
        directory: "{{ snakeoil_local_tmp_directory }}"
        domain: "{{ snakeoil_domain }}"
        openssl_config: "{{ snakeoil_domain }}.conf"
        cert_life_time: "{{ snakeoil_life_time | int }}"

    - name: create dh.pem
      delegate_to: localhost
      become: false
      snakeoil_openssl:
        state: dhparam
        directory: "{{ snakeoil_local_tmp_directory }}"
        domain: "{{ snakeoil_domain }}"
        dhparam: "{{ snakeoil_dhparam | int }}"
  when:
    - snakeoil_expire_diff_days | int <= 10 or
      ( _certificate_created.stat is defined and
        not _certificate_created.stat.exists )

- name: check for created pem {{ snakeoil_local_tmp_directory }}/{{ snakeoil_domain }}/{{ snakeoil_domain }}.pem
  delegate_to: localhost
  become: false
  stat:
    path: "{{ snakeoil_local_tmp_directory }}/{{ snakeoil_domain }}/{{ snakeoil_domain }}.pem"
  register: _certificate_created

- block:
    - name: compress directory {{ snakeoil_local_tmp_directory }}
      delegate_to: localhost
      become: false
      archive:
        path: "{{ snakeoil_local_tmp_directory }}/{{ snakeoil_domain }}"
        dest: "{{ snakeoil_local_tmp_directory }}/../{{ current_date }}_{{ snakeoil_domain }}.tgz"
        mode: 0660

    - name: propagate {{ current_date }}_{{ snakeoil_domain }}.tgz
      become: true
      copy:
        src: "{{ snakeoil_local_tmp_directory }}/../{{ current_date }}_{{ snakeoil_domain }}.tgz"
        dest: "{{ snakeoil_remote_tmp_directory }}/"
        mode: 0660

    - name: create {{ snakeoil_extract_to }}
      file:
        path: "{{ snakeoil_extract_to }}"
        state: directory
        mode: 0750

    - name: extract {{ current_date }}_{{ snakeoil_domain }}.tgz
      unarchive:
        src: "{{ snakeoil_remote_tmp_directory }}/{{ current_date }}_{{ snakeoil_domain }}.tgz"
        dest: "{{ snakeoil_extract_to }}"
        remote_src: true
  tags:
    - snakeoil
  when:
    - snakeoil_extract_to is defined
    - snakeoil_extract_to | length != 0
    - _certificate_created.stat is defined
    - _certificate_created.stat.exists
