---

- name: converge
  hosts: instance
  gather_facts: true
  become: false
  any_errors_fatal: true

  pre_tasks:
    - name: environment
      ansible.builtin.debug:
        msg:
          - "os family            : {{ ansible_distribution }} ({{ ansible_os_family }})"
          - "ansible version      : {{ ansible_version.full }}"
          - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"

  post_tasks:
    - name: environment
      ansible.builtin.debug:
        msg:
          - "os family            : {{ ansible_distribution }} ({{ ansible_os_family }})"
          - "ansible version      : {{ ansible_version.full }}"
          - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"
  roles:
    - role: ansible-snakeoil

